[package]
name = "catbox"
description = "Implementation of Catbox.moe's API"
version = "0.3.0"
edition = "2021"
homepage = "https://github.com/Savolae/catbox"
repository = "https://github.com/Savolae/catbox"
readme = "README.md"
license = "MIT"
keywords = ["file-upload", "file-hosting"]
categories = ["command-line-utilities", "filesystem", "api-bindings"]

[dependencies]
clap = { version = "*", default-features = false }
regex = "*"
reqwest = { version = "*", features = ["multipart", "stream"] }
tokio = { version = "*", features = ["full"] }
tokio-util = { version = "*", features = ["io"] }

[dev-dependencies]
tempfile = "*"
sha2 = "*"

[lib]
name = "catbox"
path = "src/lib/lib.rs"

[[bin]]
name = "catbox"
path = "src/main.rs"

[profile.release]
opt-level = 'z'
lto = true
