name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    environment: catbox
    strategy:
      matrix:
        name: [
          linux,
          windows
        ]

        include:
        - name: linux
          os: ubuntu-latest
          artifact_name: target/release/catbox
        - name: windows
          os: windows-latest
          artifact_name: target/release/catbox.exe

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build
      run: cargo build --release --locked

    - name: Make Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ matrix.artifact_name }}

  publish:
    name: Publish crate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolschain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Publish crate
      env:
        CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
    - run: cargo login ${CRATES_IO_TOKEN}
    - run: cargo publish
