name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
          linux,
          windows,
          macos
        ]

        include:
        - name: linux
          os: ubuntu-latest
          artifact_name: target/release/catbox
          asset_name: catbox-linux
        - name: windows
          os: windows-latest
          artifact_name: target/release/catbox.exe
          asset_name: catbox-windows
        - name: macos
          os: macos-latest
          artifact_name: target/release/catbox
          asset_name: catbox-macos

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build
      run: cargo build --release --locked

    - name: Upload to release
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.artifact_name }}
