name: Run Tests

on:
  push:
    branches: [ '*' ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  CATBOX_USER_HASH: ${{ secrets.CATBOX_USER_HASH }}

jobs:
  build:

    runs-on: ubuntu-latest
    environment: catbox

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
